site_name: UMI3D Documentation
site_url: https://umi3d.fr/     #to change to the specific home url
site_description: Documentation for the UMI3D SDK open-source project for cross device web XR experiences development

repo_url: https://github.com/UMI3D/UMI3D-SDK

copyright: Copyright 2018-2023 UMI3D Consortium

nav:
  - Home : index.md
  - "Getting Started":
    - pages/tutorials/index.md
    - pages/tutorials/first-steps-umi3d-edk.md

  - "How-to guides": 
    - pages/how-to/index.md
    - pages/how-to/install-sdk.md
    - pages/how-to/add-a-3d-model.md
    - pages/how-to/move-an-asset-at-runtime.md
    - pages/how-to/change-color-asset.md
    # - pages/how-to/create-asset-bundles.md
    - pages/how-to/group-assets-library.md

  - "API Reference": 
    - pages/api-reference/index.md
    - pages/api-reference/environment-description.md
    - pages/api-reference/environment-synchronization.md

  - Explanations: 
    - pages/explanation/index.md

  - About:
    - Consortium: https://umi3d-consortium.org/
    - License: pages/about/license.md

theme:
  name: material
  language: en
  favicon: img/favicon.ico
  logo: img/UMI3D-logo.png

  features:
    - navigation.path
    - navigation.instant
    - navigation.indexes

    - content.code.copy
    - content.code.annotate 

  palette:

      # Palette toggle for light mode
    - media: "(light)"
      scheme: default
      primary: cyan
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(dark)"
      scheme: slate
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

      # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.emoji:
      #already referenced in material plugin:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
