site_name: UMI3D Documentation
site_url: https://umi3d.fr/     #to change to the specific home url
site_description: Documentation for the UMI3D SDK open-source project for cross device web XR experiences development

repo_url: https://github.com/UMI3D/UMI3D-SDK

copyright: Copyright 2018-2023 UMI3D Consortium

nav:
  - "Getting Started":
    - pages/tutorials/index.md
    - pages/tutorials/first-steps-umi3d-edk.md

  - "How-to guides": 
    - pages/how-to/index.md
    - pages/how-to/install-sdk.md
    - pages/how-to/add-a-3d-model.md
    - pages/how-to/move-an-asset-at-runtime.md
    - pages/how-to/change-color-asset.md
    - pages/how-to/create-asset-bundles.md
    - pages/how-to/group-assets-library.md

  - "API Reference": 
    - pages/api-reference/index.md
    - pages/api-reference/environment-description.md
    - pages/api-reference/environment-synchronization.md

  - "Explanations": 
    - pages/explanation/index.md

  - Consortium: https://umi3d-consortium.org/

  - About:
    - License: pages/about/license.md

theme:
  name: material
  language: en
  favicon: img/favicon.ico
  logo: img/UMI3D-logo.png

  features:
    - navigation.path
    - navigation.instant
    - navigation.indexes

    - content.code.copy

  palette:

      # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: cyan
      accent: light blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

      # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight